version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/challenge
      - S3_BUCKET_NAME=local-bucket
      - S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ACCESS_KEY_ID=dummy
    depends_on:
      - mongodb

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
  
  serverless:
    build:
      context: ./serverless-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/challenge
    volumes:
      - ./serverless-app:/app
    depends_on:
      - mongodb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack-data:/var/lib/localstack

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: challenge
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  serverless_app:
  localstack-data: